modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Apache License"

[[mods]]
modId = "totem"
version = "${version}"
displayName = "TotemMod"
authors = "GingkoTreeX"
description = '''
A free and open-source cheat mod written in Java
'''
#logoFile = ""

[[dependencies.totem]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
